--SELECT TOP 20  NUMERO_MICROCHIP,NUMERO_REGISTRO FROM FEH_REGISTROS WHERE NUMERO_MICROCHIP IS NOT NULL ORDER BY NEWID()--
CREATE PROCEDURE [dbo].[APP_GetHorsesWithoutFilters](	@FkAccount	INT,
												@Start		INT,
												@Fetch		INT,
												@Search		VARCHAR(40))
AS BEGIN
	DECLARE	
		@InitFetch	INT,
		@TotalRows	INT;

	SET @InitFetch = @Fetch

	BEGIN TRY
		DROP TABLE	#TMP_ALL_MY_HORSES
		DROP TABLE	#TMP_OTHERS_WITH_PHOTO
		DROP TABLE	#TMP_OTHERS_WITHOUT_PHOTO
		DROP TABLE	#TMP_RESULT
		DROP TABLE	#TMP_PHOTOS
	END TRY
	BEGIN CATCH
		PRINT ''
	END CATCH

	CREATE TABLE #TMP_RESULT	(NUMERO_REGISTRO INT,NOMBRE_EJEMPLAR VARCHAR(60), NOMBRE_TIPO_ANDAR VARCHAR(60),NOMBRE_SEXO VARCHAR(10),NUMERO_MICROCHIP VARCHAR(16), 
								UrlMainPhoto Varchar(100),MyHorse INT,NUMERO_REGISTRO_PADRE	INT,NUMERO_REGISTRO_MADRE INT,NOMBRE_PADRE VARCHAR(60),NOMBRE_MADRE VARCHAR(60),
								[Year] INT,Color VARCHAR(30),Months INT,BornDate VARCHAR(10),Breeder VARCHAR(200),Association VARCHAR(3),CODIGO_ASOCIACION_ACTUAL VARCHAR(2),Genotyping VARCHAR(2),EquineType VARCHAR(1))

	CREATE TABLE #TMP_ALL_MY_HORSES	(NUMERO_REGISTRO INT,NOMBRE_EJEMPLAR VARCHAR(60), NOMBRE_TIPO_ANDAR VARCHAR(60),NOMBRE_SEXO VARCHAR(10),NUMERO_MICROCHIP VARCHAR(16), 
					UrlMainPhoto Varchar(100),MyHorse INT,NUMERO_REGISTRO_PADRE	INT,NUMERO_REGISTRO_MADRE INT,NOMBRE_PADRE VARCHAR(60),NOMBRE_MADRE VARCHAR(60),[Year] INT,Color VARCHAR(30),
					Months INT,BornDate VARCHAR(10),Breeder VARCHAR(200),Association VARCHAR(3),CODIGO_ASOCIACION_ACTUAL VARCHAR(2),Genotyping VARCHAR(2),EquineType VARCHAR(1))

	CREATE TABLE #TMP_OTHERS_WITH_PHOTO	(NUMERO_REGISTRO INT,NOMBRE_EJEMPLAR VARCHAR(60), NOMBRE_TIPO_ANDAR VARCHAR(60),NOMBRE_SEXO VARCHAR(10),NUMERO_MICROCHIP VARCHAR(16), 
					UrlMainPhoto Varchar(100),MyHorse INT,NUMERO_REGISTRO_PADRE	INT,NUMERO_REGISTRO_MADRE INT,NOMBRE_PADRE VARCHAR(60),NOMBRE_MADRE VARCHAR(60),[Year] INT,Color VARCHAR(30),
					Months INT,BornDate VARCHAR(10),Breeder VARCHAR(200),Association VARCHAR(3),CODIGO_ASOCIACION_ACTUAL VARCHAR(2),Genotyping VARCHAR(2),EquineType VARCHAR(1))

	CREATE TABLE #TMP_OTHERS_WITHOUT_PHOTO	(NUMERO_REGISTRO INT,NOMBRE_EJEMPLAR VARCHAR(60), NOMBRE_TIPO_ANDAR VARCHAR(60),NOMBRE_SEXO VARCHAR(10),NUMERO_MICROCHIP VARCHAR(16), 
					UrlMainPhoto Varchar(100),MyHorse INT,NUMERO_REGISTRO_PADRE	INT,NUMERO_REGISTRO_MADRE INT,NOMBRE_PADRE VARCHAR(60),NOMBRE_MADRE VARCHAR(60),[Year] INT,
					Color VARCHAR(30),Months INT,BornDate VARCHAR(10),Breeder VARCHAR(200),Association VARCHAR(3),CODIGO_ASOCIACION_ACTUAL VARCHAR(2),Genotyping VARCHAR(2),EquineType VARCHAR(1))
	
	DECLARE 
		@ByName BIT;
	
	--LISTADO DE TODAS LAS FOTOS ASOCIADAS A LOS EJEMPLARES
	SELECT	RutaFoto,Fkejemplar
	INTO #TMP_PHOTOS
	FROM	dbo.APP_EJEMPLAR_FOTO
	WHERE	PkEjemplarFoto IN	(SELECT MAX(PkEjemplarFoto)
								FROM	APP_EJEMPLAR_FOTO
								GROUP BY FkEjemplar)	
	
	SET @Search = LTRIM(RTRIM(@Search))
	
	--CONSULTAS PARA OBTENER LISTADO DE CABALLOS ASOCIADOS AL USUARIO CON FOTO
	SET @ByName = 1;

	--NO HAY FILTROS
	IF (LEN(@Search) = 0) BEGIN
		SET @ByName = 0;
		INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
			SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
					CAB.NOMBRE_EJEMPLAR,
					NDA.NOMBRE_TIPO_ANDAR, 
					CAB.CODIGO_SEXO,
					ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
					FOT.RutaFoto	AS UrlMainPhoto,
					1			AS	MyHorse,
					ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
					ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
					(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
					(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
					YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
					COL.NOMBRE_COLOR			AS	Color,
					DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
					CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
					'                                                                                                                                                                                                        '	AS Breeder,
					'   '	AS Association,
					CAB.CODIGO_ASOCIACION_ACTUAL,
					CAB.GRADO_GENO,
					CAB.CODIGO_TIP_EQUINO
			FROM	dbo.FEH_REGISTROS AS		CAB 
			INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR		=	COL.CODIGO_COLOR)
			INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR	=	NDA.CODIGO_TIPO_ANDAR)
			INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO		=	CUE.FkEjemplar)
			INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO	=	FOT.FkEjemplar)
			WHERE	CUE.FkAccount	= @FkAccount
			ORDER BY CAB.NUMERO_REGISTRO DESC
			OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;
	END

	--DEBE HACER EL FILTRO POR NUMERO_REGISTRO
	IF (LEN(@Search) >= 1 
		AND (SELECT	CASE	
						WHEN @Search LIKE '%[^-+ 0-9]%' THEN 0
						ELSE 1
					END) = 1) BEGIN
		SET @ByName = 0;
				
		INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
			SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
					CAB.NOMBRE_EJEMPLAR,
					NDA.NOMBRE_TIPO_ANDAR, 
					CAB.CODIGO_SEXO,
					ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
					FOT.RutaFoto	AS UrlMainPhoto,
					1			AS	MyHorse,
					ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
					ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
					(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
					(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
					YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
					COL.NOMBRE_COLOR			AS	Color,
					DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
					CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
					'                                                                                                                                                                                                        '	AS Breeder,
					'   '	AS Association,
					CAB.CODIGO_ASOCIACION_ACTUAL,
					CAB.GRADO_GENO,
					CAB.CODIGO_TIP_EQUINO
			FROM	dbo.FEH_REGISTROS AS		CAB 
			INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
			INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
			INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
			INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
			WHERE	CUE.FkAccount	= @FkAccount
					AND NUMERO_REGISTRO = CONVERT(NUMERIC(10,0),@Search)
	END
 
	--FILTRO POR ANDAR
	IF (@Search = 'P1' OR @Search = 'P2' OR @Search = 'P3' OR @Search = 'P4' OR @Search = 'P5') BEGIN
		SET @ByName = 0;
		INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
			SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
					CAB.NOMBRE_EJEMPLAR,
					NDA.NOMBRE_TIPO_ANDAR, 
					CAB.CODIGO_SEXO,
					ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
					FOT.RutaFoto	AS UrlMainPhoto,
					1			AS	MyHorse,
					ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
					ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
					(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
					(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
					YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
					COL.NOMBRE_COLOR			AS	Color,
					DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
					CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
					'                                                                                                                                                                                                        '	AS Breeder,
					'   '	AS Association,
					CAB.CODIGO_ASOCIACION_ACTUAL,
					CAB.GRADO_GENO,
					CAB.CODIGO_TIP_EQUINO
			FROM	dbo.FEH_REGISTROS AS		CAB 
			INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
			INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
			INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
			INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
			WHERE	CUE.FkAccount	= @FkAccount
					AND CAB.CODIGO_TIPO_ANDAR = @Search
			ORDER BY CAB.NUMERO_REGISTRO DESC
			OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;	
	END

	--FILTRO POR MICROCHIP
	IF (@Search LIKE 'AVID%') BEGIN
		SET @ByName = 0;
		INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
			SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
					CAB.NOMBRE_EJEMPLAR,
					NDA.NOMBRE_TIPO_ANDAR, 
					CAB.CODIGO_SEXO,
					ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
					FOT.RutaFoto	AS UrlMainPhoto,
					1			AS	MyHorse,
					ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
					ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
					(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
					(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
					YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
					COL.NOMBRE_COLOR			AS	Color,
					DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
					CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
					'                                                                                                                                                                                                        '	AS Breeder,
					'   '	AS Association,
					CAB.CODIGO_ASOCIACION_ACTUAL,
					CAB.GRADO_GENO,
					CAB.CODIGO_TIP_EQUINO
			FROM	dbo.FEH_REGISTROS AS		CAB 
			INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
			INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
			INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
			INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
			WHERE	CUE.FkAccount	= @FkAccount
					AND CAB.NUMERO_MICROCHIP = @Search
			ORDER BY CAB.NUMERO_REGISTRO DESC
			OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;	
	END
	--FIN FILTRO MICROCHIP

	IF (@ByName = 1) BEGIN
		INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
			SELECT	CAB.NUMERO_REGISTRO, 
					CAB.NOMBRE_EJEMPLAR,
					NDA.NOMBRE_TIPO_ANDAR, 
					CAB.CODIGO_SEXO,
					ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
					FOT.RutaFoto	AS UrlMainPhoto,
					1			AS	MyHorse,
					ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
					ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
					(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
					(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
					YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
					COL.NOMBRE_COLOR			AS	Color,
					DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
					CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
					'                                                                                                                                                                                                        '	AS Breeder,
					'   '	AS Association,
					CAB.CODIGO_ASOCIACION_ACTUAL,
					CAB.GRADO_GENO,
					CAB.CODIGO_TIP_EQUINO
			FROM	dbo.FEH_REGISTROS AS		CAB 
			INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
			INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
			INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
			INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
			WHERE	CUE.FkAccount	= @FkAccount
					AND NOMBRE_EJEMPLAR LIKE '%'+@Search+'%'
			--ORDER BY NOMBRE_EJEMPLAR DESC
			ORDER BY PATINDEX('%' + @Search + '%', NOMBRE_EJEMPLAR) ASC
			OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;
	END
		
	SELECT	@Fetch = @InitFetch - COUNT(*)
	FROM	#TMP_ALL_MY_HORSES
	--FIN CONSULTAS PARA OBTENER LISTADO DE CABALLOS ASOCIADOS AL USUARIO CON FOTO
	
	--CONSULTA PARA OBTEBER LOS CABALLOS DEL USUARIO SIN FOTO
	IF (@Fetch >= 1) BEGIN
		SET @ByName = 1;

		--FILTRO POR MICROCHIP
	IF (@Search LIKE 'AVID%') BEGIN
		SET @ByName = 0;
			
			INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						1			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
				WHERE	CUE.FkAccount	= @FkAccount
						AND CAB.NUMERO_MICROCHIP = @Search
						AND CAB.NUMERO_REGISTRO	NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
				ORDER BY CAB.NUMERO_REGISTRO DESC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;	
	END
	--FIN FILTRO MICROCHIP

		--NO HAY FILTROS
		IF (LEN(@Search) = 0) BEGIN
			SET @ByName = 0;
		
			INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						1			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR		=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR	= NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO		= CUE.FkEjemplar)
				WHERE	CUE.FkAccount	= @FkAccount
						AND CAB.NUMERO_REGISTRO NOT IN (SELECT TF.FkEjemplar FROM #TMP_PHOTOS TF)
				ORDER BY CAB.NUMERO_REGISTRO DESC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;	
		END

		--DEBE HACER EL FILTRO POR NUMERO_REGISTRO
		IF (LEN(@Search) >= 1 
			AND (SELECT		
					CASE	
						WHEN @Search LIKE '%[^-+ 0-9]%' THEN 0
						ELSE 1
					END) = 1) BEGIN
		
			SET @ByName = 0;

			INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						1			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
				WHERE	CUE.FkAccount	= @FkAccount
						AND NUMERO_REGISTRO  = @Search
						AND CAB.NUMERO_REGISTRO	NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
		END

		--FILTRO POR ANDAR
		IF (@Search = 'P1' OR @Search = 'P2' OR @Search = 'P3' OR @Search = 'P4' OR @Search = 'P5') BEGIN
			SET @ByName = 0;

			INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						1			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
				WHERE	CUE.FkAccount	= @FkAccount
						AND CAB.CODIGO_TIPO_ANDAR = @Search
						AND CAB.NUMERO_REGISTRO	NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
				ORDER BY CAB.NUMERO_REGISTRO DESC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;	
		END

		IF (@ByName = 1) BEGIN
			INSERT INTO #TMP_ALL_MY_HORSES (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						1			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS	[Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	APP_CUENTA_EJEMPLAR		CUE	ON	(NUMERO_REGISTRO = CUE.FkEjemplar)
				WHERE	CUE.FkAccount	= @FkAccount
						AND NOMBRE_EJEMPLAR LIKE '%'+@Search+'%'
						AND CAB.NUMERO_REGISTRO	NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
				ORDER BY PATINDEX('%' + @Search + '%', NOMBRE_EJEMPLAR) ASC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;		
		END
	END
	--FIN CONSULTA PARA OBTEBER LOS CABALLOS DEL USUARIO SIN FOTO

	SELECT	@TotalRows = COUNT(*)
	FROM	#TMP_ALL_MY_HORSES

	SET	@Fetch = @InitFetch - @TotalRows;

	--CONSULTAS PARA TRAER LOS DEMAS CABALLOS QUE TENGAN FOTO
	IF (@Fetch >= 1) BEGIN
		SET @ByName = 1;

		
		--NO HAY FILTROS
		IF (LEN(@Search) = 0) BEGIN
			SET @ByName = 0;

			INSERT INTO #TMP_OTHERS_WITH_PHOTO (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS	NUMERO_MICROCHIP,
						FOT.RutaFoto	AS UrlMainPhoto,
						0			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS [Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
				WHERE	CAB.NUMERO_REGISTRO NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND CAB.NUMERO_REGISTRO	IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
				ORDER BY CAB.NUMERO_REGISTRO DESC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;

		END

		--DEBE HACER EL FILTRO POR NUMERO_REGISTRO
		IF (LEN(@Search) >=1
			AND
			(SELECT CASE	
					WHEN @Search LIKE '%[^-+ 0-9]%' THEN 0
					ELSE 1
				END) = 1) BEGIN
			SET @ByName = 0;
		
			INSERT INTO #TMP_OTHERS_WITH_PHOTO (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS	NUMERO_MICROCHIP,
						FOT.RutaFoto	AS UrlMainPhoto,
						0			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS [Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
				WHERE	CAB.NUMERO_REGISTRO NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND CAB.NUMERO_REGISTRO	IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND NUMERO_REGISTRO = CONVERT(NUMERIC(10,0),@Search)

		END
		
		--FILTRO MICROCHIP
		IF (@Search LIKE 'AVID%') BEGIN
			SET @ByName = 0;
			INSERT INTO #TMP_OTHERS_WITH_PHOTO (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS	NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						0			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS [Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
				WHERE	CAB.NUMERO_REGISTRO NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND CAB.NUMERO_REGISTRO	IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND CAB.NUMERO_MICROCHIP = @Search
				ORDER BY CAB.NUMERO_REGISTRO DESC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;
		END
		--FIN FILTRO MICROCHIP
		
		--FILTRO POR ANDAR
		IF (@Search = 'P1' OR @Search = 'P2' OR @Search = 'P3' OR @Search = 'P4' OR @Search = 'P5') BEGIN
			SET @ByName = 0;

			INSERT INTO #TMP_OTHERS_WITH_PHOTO (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	DISTINCT CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS	NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						0			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS [Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
				WHERE	CAB.NUMERO_REGISTRO NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND CAB.NUMERO_REGISTRO	IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND CAB.CODIGO_TIPO_ANDAR = @Search
				ORDER BY CAB.NUMERO_REGISTRO DESC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;
		END

		IF (@ByName = 1) BEGIN
			INSERT INTO #TMP_OTHERS_WITH_PHOTO (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS	NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						0			AS	MyHorse,
						ISNULL(NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS [Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	dbo.FEH_REGISTROS AS		CAB 
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				INNER JOIN	#TMP_PHOTOS				FOT	ON	(CAB.NUMERO_REGISTRO = FOT.FkEjemplar)
				WHERE	CAB.NUMERO_REGISTRO NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND CAB.NUMERO_REGISTRO	IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND NOMBRE_EJEMPLAR LIKE '%'+@Search+'%'
				--ORDER BY NOMBRE_EJEMPLAR DESC
				ORDER BY PATINDEX('%' + @Search + '%', NOMBRE_EJEMPLAR) ASC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;	
		END

		SELECT	@TotalRows = @TotalRows + COUNT(*)
		FROM	#TMP_OTHERS_WITH_PHOTO

		SET @Fetch = @Fetch - @TotalRows
	END
	--FIN CONSULTAS PARA TRAER LOS DEMAS CABALLOS QUE TENGAN FOTO

	
	--CONSULTA LOS DEMAS CABALLOS SIN FOTO
	IF (@Fetch >= 1) BEGIN
			SET @ByName = 1;

		SELECT TOP 1 *
		INTO	#TMP_CABALLOS
		FROM	FEH_REGISTROS
		WHERE	NUMERO_REGISTRO = -1

		--NO HAY FILTROS
		IF (LEN(@Search) = 0) BEGIN
			SET @ByName = 0;

			INSERT INTO #TMP_CABALLOS
				SELECT  *
				FROM	dbo.FEH_REGISTROS REG
				WHERE	REG.NUMERO_REGISTRO			NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND REG.NUMERO_REGISTRO		NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
		END

		--DEBE HACER EL FILTRO POR NUMERO_REGISTRO
		IF (LEN(@Search) >= 1 
			AND (SELECT		
					CASE	
						WHEN @Search LIKE '%[^-+ 0-9]%' THEN 0
						ELSE 1
					END) = 1) BEGIN
		
			SET @ByName = 0;

			INSERT INTO #TMP_CABALLOS
				SELECT  *
				FROM	dbo.FEH_REGISTROS REG
				WHERE	REG.NUMERO_REGISTRO			NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND REG.NUMERO_REGISTRO		NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND REG.NUMERO_REGISTRO = CONVERT(NUMERIC(10,0), @Search)
		END

		--FILTRO MICROCHIP
		IF (@Search LIKE 'AVID%') BEGIN 
			SET @ByName=0;
			INSERT INTO #TMP_CABALLOS
			SELECT  *
				FROM	dbo.FEH_REGISTROS REG
				WHERE	REG.NUMERO_REGISTRO			NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND REG.NUMERO_REGISTRO		NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND REG.NUMERO_MICROCHIP = @Search
		END
		--FIN FILTRO MICROCHIP

		--FILTRO POR ANDAR
		IF (@Search = 'P1' OR @Search = 'P2' OR @Search = 'P3' OR @Search = 'P4' OR @Search = 'P5') BEGIN
			SET @ByName=0;

			INSERT INTO #TMP_CABALLOS
				SELECT  *
				FROM	dbo.FEH_REGISTROS REG
				WHERE	REG.NUMERO_REGISTRO			NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND REG.NUMERO_REGISTRO		NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND REG.CODIGO_TIPO_ANDAR = @Search
		END


		IF (@ByName = 1) BEGIN
			INSERT INTO #TMP_CABALLOS
				SELECT  *
				FROM	dbo.FEH_REGISTROS REG
				WHERE	REG.NUMERO_REGISTRO			NOT IN (SELECT AMH.NUMERO_REGISTRO FROM #TMP_ALL_MY_HORSES AMH)
						AND REG.NUMERO_REGISTRO		NOT IN (SELECT PHO.FkEjemplar FROM #TMP_PHOTOS PHO)
						AND NOMBRE_EJEMPLAR LIKE '%'+@Search+'%'
		END

		INSERT INTO #TMP_OTHERS_WITHOUT_PHOTO (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
				SELECT	CAB.NUMERO_REGISTRO, 
						CAB.NOMBRE_EJEMPLAR,
						NDA.NOMBRE_TIPO_ANDAR, 
						CAB.CODIGO_SEXO,
						ISNULL(CAB.NUMERO_MICROCHIP,'') AS	NUMERO_MICROCHIP,
						'                                                                                                    '	AS UrlMainPhoto,
						0			AS	MyHorse,
						ISNULL(CAB.NUMERO_REGISTRO_PADRE,0) AS NUMERO_REGISTRO_PADRE,
						ISNULL(CAB.NUMERO_REGISTRO_MADRE,0) AS NUMERO_REGISTRO_MADRE,
						(SELECT PADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS PADRE WHERE PADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_PADRE) AS NOMBRE_PADRE,
						(SELECT MADRE.NOMBRE_EJEMPLAR FROM dbo.FEH_REGISTROS MADRE WHERE MADRE.NUMERO_REGISTRO = CAB.NUMERO_REGISTRO_MADRE) AS NOMBRE_MADRE,
						YEAR(CAB.FECHA_NACIMIENTO)	AS [Year],
						COL.NOMBRE_COLOR			AS	Color,
						DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE())	AS	Months,
						CONVERT(VARCHAR(10),FECHA_NACIMIENTO,126)	AS	BornDate,
						'                                                                                                                                                                                                        '	AS Breeder,
						'   '	AS Association,
						CAB.CODIGO_ASOCIACION_ACTUAL,
						CAB.GRADO_GENO,
						CAB.CODIGO_TIP_EQUINO
				FROM	#TMP_CABALLOS				CAB
				INNER JOIN dbo.FEB_COLORES			COL	ON	(CAB.CODIGO_COLOR	=	COL.CODIGO_COLOR)
				INNER JOIN dbo.FEB_TIPOS_ANDAR		NDA ON	(CAB.CODIGO_TIPO_ANDAR = NDA.CODIGO_TIPO_ANDAR)
				--ORDER BY CAB.NUMERO_REGISTRO DESC
				ORDER BY PATINDEX('%' + @Search + '%', NOMBRE_EJEMPLAR) ASC
				OFFSET @Start ROWS FETCH NEXT @Fetch ROWS ONLY;

		DROP TABLE #TMP_CABALLOS;
	END
	--FIN CONSULTA LOS DEMAS CABALLOS SIN FOTO

	
	--INSERTA AL RESULTADO FINAL LOS EJEMPLARES DE USUARIO CON FOTO
	INSERT INTO #TMP_RESULT (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
		SELECT	NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType
		FROM	#TMP_ALL_MY_HORSES	
		WHERE	UrlMainPhoto <> ''	

	--INSERTA AL RESULTADO FINAL LOS EJEMPLARES DE USUARIO SIN FOTO
	INSERT INTO #TMP_RESULT (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
		SELECT	NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType
		FROM	#TMP_ALL_MY_HORSES	
		WHERE	UrlMainPhoto = ''

	--INSERTA AL RESULTADO FINAL LOS EJEMPLARES AJENOS AL USUARIO CON FOTO
	INSERT INTO #TMP_RESULT (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
		SELECT	NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType
		FROM	#TMP_OTHERS_WITH_PHOTO
		
	--INSERTA AL RESULTADO FINAL LOS EJEMPLARES AJENOS AL USUARIO SIN FOTO
	INSERT INTO #TMP_RESULT (NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType)
		SELECT	NUMERO_REGISTRO, NOMBRE_EJEMPLAR, NOMBRE_TIPO_ANDAR,NOMBRE_SEXO,NUMERO_MICROCHIP, UrlMainPhoto, MyHorse,NUMERO_REGISTRO_PADRE,NUMERO_REGISTRO_MADRE,NOMBRE_PADRE,NOMBRE_MADRE,[Year],Color,Months,BornDate,Breeder,Association,CODIGO_ASOCIACION_ACTUAL,Genotyping,EquineType
		FROM	#TMP_OTHERS_WITHOUT_PHOTO	
		
	
	UPDATE	#TMP_RESULT
	SET		Breeder = PR.NOMBRE_TERCERO+' '+PR.APELLIDO_TERCERO
	FROM	[dbo].[FAV_PROPIERATIOS_APP] PR
	WHERE	PR.NUMERO_REGISTRO = #TMP_RESULT.NUMERO_REGISTRO
	

	UPDATE	#TMP_RESULT
	SET		Association = SO.INICIALES
	FROM	FEB_ASOCIACIONES	SO
	WHERE	SO.CODIGO_ASOCIACION = #TMP_RESULT.CODIGO_ASOCIACION_ACTUAL
	
	SELECT	DISTINCT NUMERO_REGISTRO			AS	PkHorse, 
			NOMBRE_EJEMPLAR			AS	Name, 
			NOMBRE_TIPO_ANDAR		AS	Walk,
			CASE
				WHEN NOMBRE_SEXO = '1' THEN 'M'
				ELSE 'H'
			END						AS	Gender,
			NUMERO_MICROCHIP		AS	Microchip, 
			UrlMainPhoto,
			MyHorse,
			NUMERO_REGISTRO_PADRE	AS	Pkfather	,
			NUMERO_REGISTRO_MADRE	AS	PkMother,
			ISNULL(NOMBRE_PADRE,'') AS	NameFather,
			ISNULL(NOMBRE_MADRE,'') AS	NameMother,
			ISNULL([Year],0)		AS	[Year],
			Color,
			ISNULL(Months,0)		AS Months,
			ISNULL(BornDate,'N/R')		AS BornDate,
			Breeder,
			Association,
			Genotyping,
			EquineType
	FROM	#TMP_RESULT
	ORDER BY MyHorse DESC, UrlMainPhoto DESC
	
	EXEC APP_GH_COUNT @Search

	BEGIN TRY
		DROP TABLE	#TMP_ALL_MY_HORSES
		DROP TABLE	#TMP_OTHERS_WITH_PHOTO
		DROP TABLE	#TMP_OTHERS_WITHOUT_PHOTO
		DROP TABLE	#TMP_RESULT
		DROP TABLE	#TMP_PHOTOS
	END TRY
	BEGIN CATCH
		PRINT ''
	END CATCH
END

--EXEC APP_GetHorsesWithoutFilters 40,0,10,'PODEROSA'

--SELECT TOP 10 * FROM FEH_REGISTROS

/*DECLARE @X VARCHAR(100)
SET @X='LA REINA DEL CHIRINGUCHI'
SELECT @X WHERE @X LIKE '%%'*/

/*SELECT TOP 10 * FROM dbo.FEH_REGISTROS WHERE MONTH(FECHA_NACIMIENTO)=8 ORDER BY NEWID()

SELECT	DATEDIFF(MONTH,FECHA_NACIMIENTO,GETDATE()) AS MESES,FECHA_NACIMIENTO
FROM	dbo.FEH_REGISTROS
WHERE NUMERO_REGISTRO IN (84721,293260,93219,228057,228831,325347)*/


--SELECT * FROM ASOCIACION

/*ALTER TABLE ASOCIACION 
	ADD INICIALES VARCHAR(3) NULL*/



/*SELECT * FROM ASOCIACION
SELECT * FROM FEB_ASOCIACIONES*/

--EXEC APP_GetHorsesWithoutFilters 1000,0,20,'AVID*067*060*857'
GO


