ALTER PROCEDURE [dbo].[APP_GetParticipationRecord](	@PkHorse	INT,
													@Year		INT)
AS
BEGIN
	SELECT	FRR.FERIA,
			FRR.GRADO,
			ISNULL(TIA.NOMBRE_TIPO_ANDAR,'')		AS	ANDAR,
			FRR.ANDAR,
			FRR.CATEGORIA,
			ISNULL(FRR.PUESTO,0)					AS	PUESTO,
			ZON.NOMBRE_ZONA							AS	ZONA, 
			ISNULL(FRR.PUNTOS_EJ, 0) + ISNULL(FRR.PUNTOS_CRI, 0) + ISNULL(FRR.PUNTOS_EXP,0) AS PUNTOS
	FROM	[dbo].[FEV_REPORTE_RECORD]	FRR 
	INNER JOIN FEB_ZONAS				ZON	ON	(FRR.ZONA	=	ZON.CODIGO_ZONA)
	INNER JOIN FEB_TIPOS_ANDAR			TIA	ON	('P'+CONVERT(VARCHAR(2),FRR.ANDAR)	=	TIA.CODIGO_TIPO_ANDAR)
	WHERE	REGISTRO = @PkHorse	
			AND AÑO = @Year
END					
GO




