

CREATE PROCEDURE [dbo].[APP_GetFairByID](	@FkAccount	INT,
											@FkFair	INT)

AS BEGIN
	SET Language 'Spanish';

		SELECT	FE.ID_FERIA				AS	PkFair,	
				FE.DESCRIPCION			AS	Name,
				CONVERT(VARCHAR(11),FE.FECHA_INICIO,113)	AS	StartDate,
				CONVERT(VARCHAR(11),FE.FECHA_FIN,113)		AS	EndDate,
				GR.NOMBRE_GRADO			AS	Grade,
				ZO.NOMBRE_ZONA			AS	Zona,
				SO.SIGLA				AS	Asociation,
				ISNULL(FF.UrlPhoto,'')	AS	UrlPhoto,
				ISNULL(AA.FkAccount,0)	AS	UploadPhoto
		FROM	[dbo].[FEH_FERIAS]				FE
		INNER JOIN	[dbo].[FEB_GRADOS_FERIA]	GR	ON	(FE.CODIGO_GRADO		=	GR.CODIGO_GRADO)		
		INNER JOIN	[dbo].[FEB_CIUDADES]		CI	ON	(FE.CODIGO_CIUDAD		=	CI.CODIGO_CIUDAD)	
		INNER JOIN	[dbo].[FEB_DEPARTAMENTOS]	DE	ON	(CI.CODIGO_DEPARTAMENTO	=	DE.CODIGO_DEPARTAMENTO)	
		LEFT JOIN	APP_URL_FAIR_PHOTO			FF	ON	(FE.ID_FERIA			=	FF.FkFair)
		INNER JOIN	FEB_ZONAS					ZO	ON	(DE.CODIGO_ZONA			=	ZO.CODIGO_ZONA)
		INNER JOIN	FEH_ASOCIA_FERIAS			AF	ON	(FE.ID_FERIA			=	AF.ID_FERIA)
		INNER JOIN	FEB_ASOCIACIONES			SO	ON	(AF.CODIGO_ASOCIACION	=	SO.CODIGO_ASOCIACION)
		LEFT JOIN	APP_AccountAssociation		AA	ON	(SO.CODIGO_ASOCIACION	=	AA.FkAssociation AND AA.FkAccount = @FkAccount) 
		WHERE FE.ID_FERIA = @FkFair
		ORDER BY FE.FECHA_INICIO DESC
END